import { WritingMetrics, SentenceAnalysis, FlaggedItem } from "../types";

// Common AI transitions to flag
const ROBOTIC_TRANSITIONS = [
  { p: "furthermore", explanation: "Overused AI transition word. Try a conversational linkage. Or simply link with a semi-colon, or start the sentence without an opening qualifier.", replacement: "also, what's more, or avoid the introductory word completely" },
  { p: "moreover", explanation: "Worn-out academic linkage prevalent in generative text layouts.", replacement: "additionally, next, or integrate directly" },
  { p: "consequently", explanation: "Formal cause-effect linkage which slows down narrative cadence.", replacement: "so, as a result, or because of this" },
  { p: "therefore", explanation: "Repetitive logical marker that AI employs to over-explain simple connections.", replacement: "thus, hence, so, or omit entirely" },
  { p: "additionally", explanation: "Formulaic text extender often used to list dry features.", replacement: "beyond this, another point is, or also" },
  { p: "in conclusion", explanation: "Predictable, rote indicator of ending blocks. Breaks the flow of modern essays.", replacement: "essentially, ultimately, or simple summary integration" },
  { p: "in summary", explanation: "Mechanical wrap-up phrase that screams automatic summarizing.", replacement: "all in all, in short" },
  { p: "it is important to note", explanation: "Pompous filler that adds no semantic value to the sentence.", replacement: "note that, or state the facts directly" },
  { p: "crucial to note", explanation: "Filler statement used by LLMs to flag emphasis unnecessarily.", replacement: "crucially, or express directly" },
  { p: "it is worth mentioning", explanation: "Rhetorical hedge that pads writing length.", replacement: "importantly, or skip entirely" },
  { p: "not only does", explanation: "Highly structured inversion frequently generated by conversational engines.", replacement: "rephrase to active voice" },
  { p: "by doing so", explanation: "Rote feedback-loop linker that slows rhythm.", replacement: "this way, or integrate into action" },
  { p: "delve into", explanation: "Extremely common LLM search-engine trigger.", replacement: "explore, dissect, analyze, uncover" },
  { p: "tapestry of", explanation: "Cliche metaphor widely flagged by AI classifiers.", replacement: "network, combination, matrix, array" },
  { p: "beacon of", explanation: "Melodramatic AI phrasing.", replacement: "sign, key figure, icon" },
  { p: "testament to", explanation: "Overused cliché in LLM summaries.", replacement: "proof of, evidence of" },
  { p: "a crucial role", explanation: "Generic framing for importance.", replacement: "influences, dictates, plays a central part" }
];

const OVERCERTAINTY_WORDS = [
  { p: "obviously", explanation: "Asserting obviousness can alienate skeptical readers; suggests a lack of empirical qualification.", replacement: "apparently, it seems, or explain why it is clear" },
  { p: "absolutely", explanation: "Absolute binary qualification that undermines nuance.", replacement: "substantially, largely, or specify criteria" },
  { p: "never", explanation: "Sweeping generalization that is rarely true in nuanced settings.", replacement: "seldom, rarely, or qualify the constraints" },
  { p: "always", explanation: "Excessive generalization. Academic or professional analyses require nuance.", replacement: "consistently, typically, in most instances" },
  { p: "undeniably", explanation: "Blocks academic critical dispute.", replacement: "compellingly, as evidence indicates" },
  { p: "unquestionably", explanation: "Rhetorically aggressive; avoids reasonable counter-arguments.", replacement: "most likely, with considerable weight" },
  { p: "certainly", explanation: "Over-asserting truth without stating backing data.", replacement: "arguably, in many settings" }
];

const VAGUE_EXAMPLES = [
  { p: "for example, imagine a scenario", explanation: "Hypothetical illustration which reads as abstract, generated filler.", replacement: "cite a real case, date, or named organization" },
  { p: "consider a hypothetical", explanation: "Hypothetical logic instead of concrete, empirical backing.", replacement: "In [Year], [Specific Project] demonstrated..." },
  { p: "for instance, a software engineer", explanation: "Stereotypical placeholder example that lacks real-world names.", replacement: "mention a specific incident, code repository, or study" },
  { p: "an illustration of this is", explanation: "Mechanical, formulaic lead-in to a generic scenario.", replacement: "this is seen in, or describe the case directly" }
];

// Helper to split text into sentences carefully (ignoring common abbreviations)
function getSentences(text: string): string[] {
  if (!text) return [];
  // Clean whitespace
  const cleanText = text.replace(/\s+/g, " ");
  // Match standard end of sentence but avoid common abbreviation dot splits: e.g., i.e., Dr., Mr., etc.
  const sentenceRegex = /[^.!?]+[.!?]+(\s|$)/g;
  const matches = cleanText.match(sentenceRegex);
  if (!matches) {
    return text.trim() ? [text.trim()] : [];
  }
  return matches.map(s => s.trim()).filter(s => s.length > 0);
}

// Helper to count words
function countWordsInSentence(sentence: string): number {
  const words = sentence.trim().split(/\s+/);
  return words.filter(w => w.length > 0).length;
}

export function analyzeText(text: string): WritingMetrics {
  const rawSentences = getSentences(text);
  const totalSentences = rawSentences.length;

  // If text is empty
  if (totalSentences === 0) {
    return {
      overallScore: 100,
      burstinessScore: 100,
      openingDiversityScore: 100,
      transitionScore: 100,
      certaintyScore: 100,
      exampleQualityScore: 100,
      repetitionScore: 100,
      sentenceLengths: [],
      flaggedItems: [],
      sentences: [],
      wordCount: 0,
      averageSentenceLength: 0
    };
  }

  // 1. Sentence Cadence & Length Dataset
  const sentencesAnalysis: SentenceAnalysis[] = rawSentences.map(s => {
    const wCount = countWordsInSentence(s);
    const words = s.split(/\s+/).filter(w => w.length > 0);
    const opener = words.length > 0 ? (words[0] + (words[1] ? " " + words[1] : "")).replace(/[^a-zA-Z\s]/g, "").trim().toLowerCase() : "";
    
    let burstinessType: "short" | "medium" | "long" = "medium";
    if (wCount <= 8) burstinessType = "short";
    else if (wCount >= 22) burstinessType = "long";

    return {
      text: s,
      length: wCount,
      opener,
      burstinessType
    };
  });

  const lengths = sentencesAnalysis.map(s => s.length);
  const totalWords = lengths.reduce((acc, l) => acc + l, 0);
  const averageLength = totalWords / totalSentences;

  // Standard Deviation calculation for BURSTINESS
  let variance = 0;
  if (totalSentences > 1) {
    const squaredDiffs = lengths.map(l => Math.pow(l - averageLength, 2));
    const sumSquaredDiffs = squaredDiffs.reduce((acc, d) => acc + d, 0);
    variance = sumSquaredDiffs / (totalSentences - 1);
  }
  const stdDev = Math.sqrt(variance);
  
  // Coefficient of Variation = stdDev / averageLength (CV encapsulates burstiness)
  const coeffOfVar = averageLength > 0 ? stdDev / averageLength : 0;
  
  // Convert standard deviation and CV to Burstiness Score (0 to 100)
  // Human CV typically ranges from 0.45 to 1.10. AI typically rests around 0.15 to 0.35.
  let burstinessScore = Math.round(Math.min((coeffOfVar / 0.7) * 100, 100));
  if (totalSentences <= 2) burstinessScore = 80; // edge case protection

  // 2. Opening Diversity (checking first words of adjacent/all sentences)
  const openers = sentencesAnalysis.map(s => s.opener);
  const uniqueOpenersCount = new Set(openers).size;
  // Score opening diversity as percentage of unique openers, adjusted
  let openingDiversityScore = totalSentences > 0 
    ? Math.round(Math.min((uniqueOpenersCount / totalSentences) * 120, 100))
    : 100;
  
  // Additional deduction for subsequent duplicate openers
  let openerRepetitions = 0;
  const openerCounts: Record<string, number> = {};
  openers.forEach(o => {
    if (!o) return;
    const baseWord = o.split(" ")[0]; // Look at single word duplicates first
    openerCounts[baseWord] = (openerCounts[baseWord] || 0) + 1;
  });
  Object.values(openerCounts).forEach(count => {
    if (count > 1) {
      openerRepetitions += (count - 1);
    }
  });
  openingDiversityScore = Math.max(openingDiversityScore - (openerRepetitions * 5), 20);

  // 3. Scan & Flag items for Transitions, Overcertainty, Repetitions
  const flaggedItems: FlaggedItem[] = [];
  const textLower = text.toLowerCase();

  // Flag transitions & AI phrases
  ROBOTIC_TRANSITIONS.forEach((trans, index) => {
    let pos = -1;
    // Simple way to check boundaries: word match
    const regex = new RegExp(`\\b${trans.p}\\b`, "gi");
    let match;
    while ((match = regex.exec(text)) !== null) {
      flaggedItems.push({
        id: `rot-${index}-${match.index}`,
        phrase: match[0],
        type: "robotic_transition",
        explanation: trans.explanation,
        replacement: trans.replacement,
        severity: "medium"
      });
    }
  });

  // Flag Over-certainties
  OVERCERTAINTY_WORDS.forEach((cert, index) => {
    const regex = new RegExp(`\\b${cert.p}\\b`, "gi");
    let match;
    while ((match = regex.exec(text)) !== null) {
      flaggedItems.push({
        id: `cert-${index}-${match.index}`,
        phrase: match[0],
        type: "overcertainty",
        explanation: cert.explanation,
        replacement: cert.replacement,
        severity: cert.p === "obviously" || cert.p === "undeniably" ? "high" : "low"
      });
    }
  });

  // Flag Vague Examples
  VAGUE_EXAMPLES.forEach((vague, index) => {
    const regex = new RegExp(`\\b${vague.p}\\b`, "gi");
    let match;
    while ((match = regex.exec(text)) !== null) {
      flaggedItems.push({
        id: `vague-${index}-${match.index}`,
        phrase: match[0],
        type: "vague_example",
        explanation: vague.explanation,
        replacement: vague.replacement,
        severity: "medium"
      });
    }
  });

  // Flag Phrase Repetitions
  // Check for duplicated word 3-grams of length 3 that appear adjacent or within 10 sentences
  const wordsArray = textLower.match(/\b([a-z]{3,})\b/gi) || [];
  const ngrams: Record<string, number[]> = {};
  for (let i = 0; i < wordsArray.length - 2; i++) {
    const ngram = `${wordsArray[i]} ${wordsArray[i+1]} ${wordsArray[i+2]}`;
    if (!ngrams[ngram]) ngrams[ngram] = [];
    ngrams[ngram].push(i);
  }
  Object.entries(ngrams).forEach(([gram, indices], index) => {
    if (indices.length > 1 && !gram.includes("it is a") && !gram.includes("there is a") && !gram.includes("of the same") && !gram.includes("as well as")) {
      // Find where in the text this phrase is
      const regex = new RegExp(gram.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&'), "gi");
      let match;
      let count = 0;
      while ((match = regex.exec(text)) !== null && count < 2) {
        if (count > 0) { // only flag the repetition
          flaggedItems.push({
            id: `rep-${index}-${match.index}`,
            phrase: match[0],
            type: "phrase_repetition",
            explanation: `The distinct 3-word phrase "${match[0]}" is repeated in close proximity. AI tends to recycle structural trigrams.`,
            replacement: "express the secondary claim with different syntactic pacing",
            severity: "low"
          });
        }
        count++;
      }
    }
  });

  // 3a. Grand Abstract Framing Detection
  const GRAND_ABSTRACT_PATTERNS = [
    { p: "by 2026", explanation: "Starts with an authoritative historical projection or grand societal prediction, a classic AI opening tell.", replacement: "In current years," },
    { p: "by 2025", explanation: "Starts with an authoritative historical projection or grand societal prediction, a classic AI opening tell.", replacement: "Recently," },
    { p: "with the fast rise of", explanation: "Broad abstract sweeping historical claim used to frame a simple concept.", replacement: "As more people adopt" },
    { p: "with the rapid rise of", explanation: "Broad abstract sweeping historical claim used to frame a simple concept.", replacement: "As more people adopt" },
    { p: "throughout human history", explanation: "Overly grandiose sweeping generic historical frame.", replacement: "Historically," },
    { p: "since the dawn of", explanation: "Melodramatic opening cliché used by AI models to introduce simple concepts.", replacement: "Originally," },
    { p: "in the era of", explanation: "Sweeping era-based prediction or abstract framing.", replacement: "With current" },
    { p: "the rapid ascent of", explanation: "Abstract historical claim.", replacement: "the adoption of" },
    { p: "the fast rise of", explanation: "Abstract historical claim.", replacement: "the growth of" }
  ];

  GRAND_ABSTRACT_PATTERNS.forEach((gap, index) => {
    const regex = new RegExp(`\\b${gap.p}\\b`, "gi");
    let match;
    while ((match = regex.exec(text)) !== null) {
      flaggedItems.push({
        id: `grand-${index}-${match.index}`,
        phrase: match[0],
        type: "grand_abstract",
        explanation: gap.explanation,
        replacement: gap.replacement,
        severity: "high"
      });
    }
  });

  // 3b. Polished Analogy Construction Detection
  const POLISHED_ANALOGIES = [
    { p: "much like the transition", explanation: "Uses a highly polished, familiar analogy for rhetorical support instead of raw analytical or empirical evidence.", replacement: "unlike the history of" },
    { p: "much like the shift", explanation: "Uses a highly polished, familiar analogy for rhetorical support instead of raw empirical evidence.", replacement: "separate from the history of" },
    { p: "similar to the transition", explanation: "Uses a highly polished comparison that behaves like predictable LLM training patterns.", replacement: "unlike the transition" },
    { p: "can be likened to", explanation: "Rhetorical comparison that simplifies complex, nuanced realities.", replacement: "shares features with" },
    { p: "parallels can be drawn", explanation: "Formulaic rhetorical comparison used as filler support.", replacement: "we can compare" },
    { p: "just as the printing press", explanation: "Extremely common and overused historical analogy found in AI texts.", replacement: "while previous technologies" }
  ];

  POLISHED_ANALOGIES.forEach((pa, index) => {
    const regex = new RegExp(`\\b${pa.p}\\b`, "gi");
    let match;
    while ((match = regex.exec(text)) !== null) {
      flaggedItems.push({
        id: `analogy-${index}-${match.index}`,
        phrase: match[0],
        type: "polished_analogy",
        explanation: pa.explanation,
        replacement: pa.replacement,
        severity: "medium"
      });
    }
  });

  // 3c. Dense Conceptual Vocabulary (Nominalizations) Detection
  const DENSE_VOCAB_TERMS = [
    { p: "generative ai", explanation: "Overused generic abstract category. Try active verbal construction.", replacement: "systems that generate text" },
    { p: "critical literacy", explanation: "Highly abstract nominalized academic buzzword.", replacement: "practical reading skills" },
    { p: "educational models", explanation: "Abstract corporate-style categorization of standard learning structures.", replacement: "ways schools teach" },
    { p: "failure modes", explanation: "Pretentious engineering terminology applied to non-technical settings to sound intellectual.", replacement: "common ways things go wrong" },
    { p: "automated systems", explanation: "Generic multi-noun conceptual stack that is passive.", replacement: "tools running themselves" },
    { p: "transactional module", explanation: "Highly synthesized conceptual nominalization.", replacement: "the buying process" },
    { p: "conceptual framing", explanation: "Abstract jargon cluster.", replacement: "perspective" },
    { p: "analytical synthesis", explanation: "Overly dense academic nominalization.", replacement: "careful review" },
    { p: "analytical evidence", explanation: "Abstract category of claim.", replacement: "data and facts" },
    { p: "rhetorical support", explanation: "Academic jargon.", replacement: "persuasiveness" },
    { p: "societal claim", explanation: "Highly abstract generic assertion.", replacement: "broad argument" }
  ];

  DENSE_VOCAB_TERMS.forEach((dv, index) => {
    const regex = new RegExp(`\\b${dv.p}\\b`, "gi");
    let match;
    while ((match = regex.exec(text)) !== null) {
      flaggedItems.push({
        id: `densev-${index}-${match.index}`,
        phrase: match[0],
        type: "dense_vocab",
        explanation: dv.explanation,
        replacement: dv.replacement,
        severity: "low"
      });
    }
  });

  // 3d. Overly Smooth Logical Progression Check
  const smoothClues = ["much like", "consequently", "therefore", "consider the", "furthermore", "moreover", "as a result"];
  let smoothHits = 0;
  smoothClues.forEach(clue => {
    if (textLower.includes(clue)) {
      smoothHits++;
    }
  });

  // Highlight if there is low cognitive pausing (punctuation/detours) combined with progressive links
  if (smoothHits >= 3 && !textLower.includes("?") && !textLower.includes("(") && !textLower.includes(";") && !textLower.includes("—")) {
    const firstSmooth = smoothClues.find(clue => textLower.includes(clue));
    if (firstSmooth) {
      const idx = textLower.indexOf(firstSmooth);
      flaggedItems.push({
        id: `smooth-progression-warning`,
        phrase: text.substring(idx, idx + firstSmooth.length),
        type: "smooth_progression",
        explanation: "Overly smooth, linear logical progression. The transitions ('Much like', 'Consequently', 'Consider') glide seamlessly without the detours, parenthetical caveats, or uneven pauses typical of real human thinking.",
        replacement: `${firstSmooth} — speaking of which, we should note that —`,
        severity: "medium"
      });
    }
  }

  // Calculate scores for specific domains from flagged frequency
  const transCount = flaggedItems.filter(f => f.type === "robotic_transition").length;
  const certCount = flaggedItems.filter(f => f.type === "overcertainty").length;
  const vagueCount = flaggedItems.filter(f => f.type === "vague_example").length;
  const repCount = flaggedItems.filter(f => f.type === "phrase_repetition").length;
  
  const grandCount = flaggedItems.filter(f => f.type === "grand_abstract").length;
  const analogyCount = flaggedItems.filter(f => f.type === "polished_analogy").length;
  const smoothCount = flaggedItems.filter(f => f.type === "smooth_progression").length;
  const denseCount = flaggedItems.filter(f => f.type === "dense_vocab").length;

  // Let's normalize deductions based on total sentences/words
  const densityMultiplierVal = totalSentences > 0 ? (10 / totalSentences) : 1;
  const densityMultiplier = Math.min(Math.max(densityMultiplierVal, 0.4), 2.5); // sanitize boundaries

  // Penalize the specific indicators
  let transitionScore = Math.max(100 - Math.round((transCount * 12 + smoothCount * 25 + analogyCount * 10) * densityMultiplier), 20);
  let certaintyScore = Math.max(100 - Math.round(certCount * 10 * densityMultiplier), 30);
  let exampleQualityScore = Math.max(100 - Math.round((vagueCount * 25 + grandCount * 30 + analogyCount * 15) * densityMultiplier), 40);
  let repetitionScore = Math.max(100 - Math.round((repCount * 8 + denseCount * 12) * densityMultiplier), 30);

  // Vocabulary richness (Type-Token Ratio) calculation
  const uniqueWords = new Set(wordsArray.map(w => w.toLowerCase())).size;
  let wordRepScore = wordsArray.length > 0 
    ? Math.round(Math.min((uniqueWords / wordsArray.length) * 150, 100))
    : 100;
  repetitionScore = Math.round((repetitionScore * 0.4) + (wordRepScore * 0.6));

  // If very few segments exist, downrate certainty or richness
  if (totalSentences < 3) {
    certaintyScore = Math.min(certaintyScore, 85);
    exampleQualityScore = Math.min(exampleQualityScore, 90);
  }

  // Deduct slightly from burstiness score if logical progression is too smooth since it lacks pauses
  let burstinessScoreAdj = burstinessScore;
  if (smoothCount > 0) {
    burstinessScoreAdj = Math.max(burstinessScore - 20, 20);
  }

  // 4. Overall Human-Likeness Score
  // Weighted calculation favoring Burstiness (the most prominent structural classifier)
  const overallScore = Math.round(
    (burstinessScoreAdj * 0.3) +
    (openingDiversityScore * 0.15) +
    (transitionScore * 0.15) +
    (certaintyScore * 0.15) +
    (exampleQualityScore * 0.15) +
    (repetitionScore * 0.1)
  );

  return {
    overallScore: Math.min(Math.max(overallScore, 10), 99), // Keep it cap at 99 because absolute perfect human score is elusive!
    burstinessScore: burstinessScoreAdj,
    openingDiversityScore,
    transitionScore,
    certaintyScore,
    exampleQualityScore,
    repetitionScore,
    sentenceLengths: lengths,
    flaggedItems,
    sentences: sentencesAnalysis,
    wordCount: totalWords,
    averageSentenceLength: parseFloat(averageLength.toFixed(1))
  };
}
